# Adds a list of words in a slot
# please refer to http://doc.aldebaran.com/2-4/naoqi/audio/alspeechrecognition-api.html#alspeechrecognition-api
string contextName 
string slotName
string[] wordList
---
bool success
