# Returns the corresponding engagement zone based on the angular coordinate
# Please refre to http://doc.aldebaran.com/2-4/naoqi/peopleperception/alengagementzones-api.html#alengagementzones-api
float64 x_angle
float64 y_angle
float64 distance
geometry_msgs/Twist camera_position_from_frame_robot
---
uint8 engagement_zone 
