# Deactivates a rule contained in the specified context
# please refer to http://doc.aldebaran.com/2-4/naoqi/audio/alspeechrecognition-api.html#alspeechrecognition-api
string contextName
string ruleName
---
bool success
