# Deletes from the database all learned faces corresponding to the specified person.
# Please refer to http://doc.aldebaran.com/2-4/naoqi/peopleperception/alfacedetection-api.html#alfacedetection-api
string name
---
bool success
