# Returns the list of the language currently used by the speech recognition system
# please refer to http://doc.aldebaran.com/2-4/naoqi/audio/alspeechrecognition-api.html#alspeechrecognition-api
---
string language
