# Get the Current Smiling Threshold for FaceCharacteristics/PersonSmiling()
# Please refere to http://doc.aldebaran.com/2-4/naoqi/peopleperception/alfacecharacteristics-api.html#alfacecharacteristics-api
---
float64 threshold
