# Get the [x, y, z] position of active target in desired frame.
# Please refer to http://doc.aldebaran.com/2-4/naoqi/trackers/altracker-api.html#altracker-api
naoqi_bridge_msgs/Frames frame
---
geometry_msgs/Point target_position
