# Get Status of Module Use of Movement Detection for ALPeoplePerception
# Please refer to http://doc.aldebaran.com/2-4/naoqi/peopleperception/alpeopleperception-api.html#alpeopleperception-api
---
bool status
