# Return true if a new target was detected since the last ALTrackerProxy::getTargetPosition.
# Please refer to http://doc.aldebaran.com/2-4/naoqi/trackers/altracker-api.html#altracker-api
---
bool status
