# Replaces the currently loaded context set by the one previously saved under the name saveName
# please refer to http://doc.aldebaran.com/2-4/naoqi/audio/alspeechrecognition-api.html#alspeechrecognition-api
string saveName
---
bool success
