# Uses, in a new learning process, the latest images where a face has been wrongly recognized.
# Please refer to http://doc.aldebaran.com/2-4/naoqi/peopleperception/alfacedetection-api.html#alfacedetection-api
string name
---
bool success
