# Set objects coordinates. Use ALTrackerProxy::getTargetCoordinates to get this value. (Only work with LandMarks target name.)
# Please refer to http://doc.aldebaran.com/2-4/naoqi/trackers/altracker-api.html#altracker-api
geometry_msgs/Twist first_object_coordinate
geometry_msgs/Twist second_object_coordinate
---
bool success
